global:
  resolve_timeout: 5m
route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'webhook'
receivers:
- name: 'webhook'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/T02ST3/BMEF5K/7DFQwU'
    channel: '#alertmgr'
